"""initial schema

Revision ID: e14c14326370
Revises: 
Create Date: 2026-09-08 08:36:14.604128
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = 'e14c14326370'
down_revision: str | None = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('ha_user_id', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_ha_user_id'), ['ha_user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_telegram_user_id'), ['telegram_user_id'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('old_data', sa.Text(), nullable=True),
    sa.Column('new_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("action IN ('create', 'update', 'delete', 'restore')", name='ck_audit_action'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('statement_day', sa.Integer(), nullable=True),
    sa.Column('due_day', sa.Integer(), nullable=True),
    sa.Column('cutoff_inclusive', sa.Boolean(), nullable=False),
    sa.Column('credit_limit_minor', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("type <> 'cash' OR (statement_day IS NULL AND due_day IS NULL)", name='ck_cash_has_no_statement_days'),
    sa.CheckConstraint("type <> 'credit_card' OR (statement_day IS NOT NULL AND due_day IS NOT NULL AND statement_day BETWEEN 1 AND 31 AND due_day BETWEEN 1 AND 31)", name='ck_credit_card_days_in_range'),
    sa.CheckConstraint("type IN ('cash', 'credit_card')", name='ck_payment_method_type'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=16), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('total_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('installment_count', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payment_method_type_snapshot', sa.String(length=16), nullable=False),
    sa.Column('payment_method_name_snapshot', sa.String(length=64), nullable=False),
    sa.Column('statement_day_snapshot', sa.Integer(), nullable=True),
    sa.Column('due_day_snapshot', sa.Integer(), nullable=True),
    sa.Column('cutoff_inclusive_snapshot', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('installment_count BETWEEN 1 AND 12', name='ck_expense_installment_range'),
    sa.CheckConstraint('total_amount_minor > 0', name='ck_expense_amount_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_payment_method_id'), ['payment_method_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_expenses_transaction_date'), ['transaction_date'], unique=False)

    op.create_table('expense_installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('installment_count', sa.Integer(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'paid', 'cancelled')", name='ck_installment_status'),
    sa.CheckConstraint('installment_number BETWEEN 1 AND installment_count', name='ck_installment_number_within_count'),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expense_id', 'installment_number', name='uq_installment_number_per_expense')
    )
    with op.batch_alter_table('expense_installments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_installments_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_installments_expense_id'), ['expense_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_installments_statement_date'), ['statement_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_installments_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_installments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_installments_status'))
        batch_op.drop_index(batch_op.f('ix_expense_installments_statement_date'))
        batch_op.drop_index(batch_op.f('ix_expense_installments_expense_id'))
        batch_op.drop_index(batch_op.f('ix_expense_installments_due_date'))

    op.drop_table('expense_installments')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_expenses_public_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_payment_method_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_expenses_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_category_id'))

    op.drop_table('expenses')
    op.drop_table('payment_methods')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_ha_user_id'))

    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
